#!/bin/sh

if git-rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

allownonascii=$(git config hooks.allownonascii)

DIR="$( cd "$( dirname "$0" )" && pwd )"
exec git diff-index --name-only --diff-filter=AM $against -- | grep '\.cpp\|\.h\|\.c\|\.hpp' | xargs $DIR/check-webkit-style --diff-files
